apiVersion: batch/v1
kind: CronJob
metadata:
  name: node-metrics-cronjob
  namespace: default
spec:
  schedule: "*/1 * * * *"  # Run every 1 minutes
  jobTemplate:
    spec:
      template:
        spec:
          nodeSelector:
            eks.amazonaws.com/nodegroup: ne_nodepool
          containers:
            - name: node-metrics-cronjob
              image: public.ecr.aws/d2v6q9t9/node_exporter:latest
              # command: ["/bin/sh", "-c", "/scripts/script.sh"]  # Command to run the script
              volumeMounts:
                - name: rootfs
                  mountPath: /host
 
              securityContext:
                runAsUser: 0  # Run the container as root
          restartPolicy: OnFailure
          volumes:
          - name: rootfs
            hostPath:
              path: /
              type: Directory