kind: Service
apiVersion: v1
metadata:
  name: node-exporter
  namespace: default
  labels:
    app: node-exporter
spec:
  selector:
    app: node-exporter
  ports:
    - port: 9100
      name: ne-port
      protocol: TCP
      targetPort: 9100
  type: ClusterIP
